### ISSUE TITLE
ERROR: NO SIGNAL DATA FOUND IN INPUTFILE 

### ISSUE THREAD

**Issue by haoziyeung** [WGLab/PennCNV-Seq#1]
hello,i have a 30X WGS sample,i'm using your PennCNV-Seq,here's my cmd:

/gpfs/users/yanghao/software/perl-5.14.2-bin/bin/perl /gpfs/users/yanghao/software/PennCNV-1.0.4/detect_cnv.pl sample.chr21.baflrr -wgs -hmmfile wgs.hmm -pfb reference/hg19_EAS.sites.2015_08.pfb -output sample.rawcnv
NOTICE: Reading marker coordinates and population frequency of B allele (PFB) from reference/hg19_EAS.sites.2015_08.pfb ... Done with 15452 records
NOTICE: Reading LRR and BAF values for from sample.chr21.baflrr ... Done with 0 records in 0 chromosomes (677293 records are discarded due to lack of PFB information for the markers)
ERROR: NO SIGNAL DATA FOUND IN INPUTFILE sample.chr21.baflrr
WARNING: Skipping sample.chr21.baflrr since no signal values can be retrieved from the file

and i upload this file for your debugging ,https://github.com/haoziyeung/supp_files/blob/master/sample.chr21.baflrr.gz , thanks a lot!

**Comment by rashindrie** [comment]
@haoziyeung Were you able to figure out how to make CNV calls from PennCNV? 

I am also running into the same issue that you have mentioned and was not able to find a solution so far. 

TIA :)

**Comment by kaichop** [comment]
This message means there is no matching record in chr21.baflrr file and the PFB file. Users are supposed to create PFB file yourself from your own dataset, (but for convenience you can certainly take gnomAD genome frequency information to build one quickly). The marker name however must match. If not, then you will see the '0 records in 0 chromosomes' message.
